### ISSUE TITLE
cannot import name 'Lumen'

### ISSUE THREAD

**Issue by RamyaChandra01** [qut-dmrc/lumenapi#1]
Hey First off thanks for this wrapper!

When I try to import I am getting this error: ImportError: cannot import name 'Lumen' from 'api' (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/api/__init__.py)

Thanks

**Comment by nicsuzor** [comment]
Thanks for the report! I've renamed the class to avoid this problem in the future. Please use:

`from lumen import Lumen`

Fixed in 0f79ba7.
